In [ ]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head(5)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [3]:
df.rename(columns={"entity": "País"}, inplace=True)

In [4]:
df.head(3)

          País code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [13]:
df.rename(columns={"code": "Código",
                   "year": "Año",
                   "life_expectancy_0": "Esperanza"}, inplace=True)

In [15]:
df.set_index("País",inplace=True)

KeyError: "None of ['País'] are in the columns"

In [16]:
df.set_index("País","Año", inplace=True)

TypeError: DataFrame.set_index() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

In [17]:
df.local(df["País"].str.contains{"U", case=False, regrex=True})

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (808459576.py, line 1)

In [18]:
df.local(df["Código"].notnull{})

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2280467789.py, line 1)

In [19]:
df.dropna(subset=["Código"], inplace=True)
df.isnull().sum()

Código       0
Año          0
Esperanza    0
dtype: int64

In [20]:
resultado {
    df.groupby("País")["Esperanza"]
    .mean()
    .sort_values(ascending=True)
}

SyntaxError: invalid syntax (238540553.py, line 1)